[workspace]
members = [
    "black_core",
    "black_train",
    "black_bind",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.75.0"
version = "0.1.0"

[workspace.dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
half = "2.4"
num-traits = "0.2"
parking_lot = "0.12"
rayon = "1.10"
thiserror = "1.0"
rand = "0.8"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
black_core = { path = "black_core" }
black_train = { path = "black_train" }

